### ISSUE TITLE
can i record 3 audio same time?

### ISSUE THREAD

**Issue by davut5** [AlesTsurko/LearningCoreAudioWithSwift2.0#1]
i am playing youtube video in uiview with Youtube Player Helper Pods.
can i  save youtube video sound + my voice + some effect (like reverb)?

**Comment by ales-tsurko** [comment]
Hi! I don't understand why you ask it here, but... I think it's better to look up solution in Youtube API and Web Audio API for such tasks.
Try to ask your question on stackoverflow.com The issue tracking of this repository is not good place for it.
