### ISSUE TITLE
hi my friend.

### ISSUE THREAD

**Issue by davut5** [AlesTsurko/LearningCoreAudioWithSwift2.0#2]
How do I record my voice with a background song playing?

ı think you solve my problem. because your sample look very nice. 

Get audio input buffers and put the output audio into the same buffers as well. i need a player to play the background song and it can mix itself and record it.
will you help me? it can be any PODS or any solution. I need it too much.

**Comment by ales-tsurko** [comment]
Hi! Here is a tutorial, which explains playback/recording audio with AVFoundation framework: http://www.rockhoppertech.com/blog/avfoundation-audio-recording-with-swift/

If you need a mixed file on the output, you could record the voice while the song is playing and then render it to the file. Regarding to mixing buffers on the fly, I can't give you an exact answer. Check out AVFoundation framework. And, please, write such questions in private.
